spring:
  application:
    name:
      keycloak

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://localhost:8080/realms/Waris
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
    port: 8081

jwt:
  auth:
    converter:
      resources-id: waris-rest-api
      principle-attribute: preferred-name